CREATE TABLE [dbo].[tblCrusher] (
    [CRUSHERNO]  VARCHAR (255) NOT NULL,
    [DFROM]      DATETIME2 (7) NOT NULL,
    [DTO]        DATETIME2 (7) NULL,
    [OPERATOR]   VARCHAR (255) NULL,
    [SUPERVISOR] VARCHAR (255) NULL,
    [REMARKS]    VARCHAR (255) NULL
);

