CREATE TABLE [dbo].[tblEmployeesInfo] (
    [employeeID]             VARCHAR (255) COLLATE Latin1_General_CI_AS NOT NULL,
    [lastname]               VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [firstname]              VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [middlename]             VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [address]                VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [contactNo]              VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [homeNo]                 VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [religion]               VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [gender]                 VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [birthdate]              DATETIME2 (7) NULL,
    [civilstatus]            VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [department]             VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [division]               VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [position]               VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [rate]                   MONEY         NULL,
    [grade]                  VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [payMethod]              VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [dateHired]              DATETIME2 (7) NULL,
    [workingStatus]          VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [field]                  VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [sssNo]                  VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [tinNo]                  VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [piNo]                   VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [phNo]                   VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [sssDedDate]             VARCHAR (255) NULL,
    [whDedDate]              VARCHAR (255) NULL,
    [piDedDate]              VARCHAR (255) NULL,
    [phDedDate]              VARCHAR (255) NULL,
    [allowBenefitsDeduction] VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [remarks]                VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [yearRes]                DATETIME      NULL
);

