CREATE TABLE [dbo].[tblInvtry] (
    [ITEMNO]         VARCHAR (255) NOT NULL,
    [ITEMDESC]       VARCHAR (255) NULL,
    [BUYABLE]        VARCHAR (255) NULL,
    [SELLABLE]       VARCHAR (255) NULL,
    [INVENTORABLE]   VARCHAR (255) NULL,
    [COSTOFSALESACC] VARCHAR (255) NULL,
    [INCOMEACC]      VARCHAR (255) NULL,
    [ASSETACC]       VARCHAR (255) NULL,
    [STATUS]         VARCHAR (255) NULL
);

