CREATE TABLE [dbo].[tblPayrollofEmployees] (
    [empPayrollTransNo]   INT           IDENTITY (1, 1) NOT NULL,
    [payrollID]           VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [employeeID]          VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [totalWorkedDays]     MONEY         NULL,
    [absent]              MONEY         NULL,
    [rhd]                 MONEY         NULL,
    [nwhd]                MONEY         NULL,
    [regHolidays]         MONEY         NULL,
    [NonWorkHolidays]     MONEY         NULL,
    [leavePay]            MONEY         NULL,
    [overtimeHRS]         MONEY         NULL,
    [restdayReportHRS]    MONEY         NULL,
    [lateUTMins]          MONEY         NULL,
    [basicPay]            MONEY         NULL,
    [regHolidayPay]       MONEY         NULL,
    [nonWorkHolidayPay]   MONEY         NULL,
    [leavePayCash]        MONEY         NULL,
    [overtimePay]         MONEY         NULL,
    [restdayReportAmount] MONEY         NULL,
    [lateUndertimeDed]    MONEY         NULL,
    [cashAdvance]         MONEY         NULL,
    [wHoldingTax]         MONEY         NULL,
    [sssPrems]            MONEY         NULL,
    [piPrems]             MONEY         NULL,
    [phPrems]             MONEY         NULL,
    [sssLoans]            MONEY         NULL,
    [piLoans]             MONEY         NULL,
    [ledgerBalance]       MONEY         NULL,
    [grossPay]            MONEY         NULL,
    [Deduction]           MONEY         NULL,
    [Netpay]              MONEY         NULL
);

