CREATE TABLE [dbo].[tblQATRS] (
    [QAITEMNO] INT           IDENTITY (1, 1) NOT NULL,
    [QANO]     VARCHAR (255) NULL,
    [1DLEFT]   VARCHAR (255) NULL,
    [1DRIGHT]  VARCHAR (255) NULL,
    [1TLEFT]   VARCHAR (255) NULL,
    [1TRIGHT]  VARCHAR (255) NULL,
    [2DLEFT]   VARCHAR (255) NULL,
    [2DRIGHT]  VARCHAR (255) COLLATE Latin1_General_CI_AS NULL,
    [2TLEFT]   VARCHAR (255) NULL,
    [2TRIGHT]  VARCHAR (255) NULL,
    [3DLEFT]   VARCHAR (255) NULL,
    [3DRIGHT]  VARCHAR (255) NULL,
    [3TLEFT]   VARCHAR (255) NULL,
    [3TRIGHT]  VARCHAR (255) NULL,
    [REMARKS]  VARCHAR (255) NULL
);

