CREATE TABLE [dbo].[tblQATR] (
    [QAITEMNO] INT           IDENTITY (1, 1) NOT NULL,
    [QANO]     VARCHAR (255) NULL,
    [AVGD1]    VARCHAR (255) NULL,
    [AVGT1]    VARCHAR (255) NULL,
    [RPM1]     VARCHAR (255) NULL,
    [AVGD2]    VARCHAR (255) NULL,
    [AVGT2]    VARCHAR (255) NULL,
    [RPM2]     VARCHAR (255) NULL,
    [AVGD3]    VARCHAR (255) NULL,
    [AVGT3]    VARCHAR (255) NULL,
    [RPM3]     VARCHAR (255) NULL,
    [REMARKS]  VARCHAR (255) NULL
);

