CREATE TABLE [dbo].[tblRecycle] (
    [RRNO]          VARCHAR (255) NOT NULL,
    [DFROM]         DATETIME2 (7) NULL,
    [DTO]           DATETIME2 (7) NULL,
    [OPERATOR]      VARCHAR (255) NULL,
    [SUPERVISOR]    VARCHAR (255) NULL,
    [TOTALINPUTWT]  VARCHAR (255) NULL,
    [TOTALOUTPUTWT] VARCHAR (255) NULL,
    [REMARKS]       VARCHAR (255) NULL
);

