CREATE PROCEDURE [dbo].[GET_ACCNO_OF_TRNO]
@COMMAND AS INT,
@SEARCHVALUE AS VARCHAR(255),
@MEMOTYPE AS VARCHAR(255)
AS
BEGIN
IF @COMMAND = 0 BEGIN
SELECT ACCNO FROM tblAccEntry WHERE REFNO = @SEARCHVALUE AND DEBIT > CREDIT AND MEMO LIKE @memotype + '%'
END
ELSE IF @COMMAND =1 BEGIN
SELECT ACCNO FROM tblAccEntry WHERE REFNO = @SEARCHVALUE AND DEBIT < CREDIT AND MEMO LIKE @memotype + '%'
END
END