CREATE PROCEDURE [dbo].[GET_ATTENDANCE_SUMMARY]
@DATEFROM AS DATETIME2,
@DATETO AS DATETIME2,
@DEPARTMENTID AS VARCHAR(255),
@sundaysCount as int
AS
BEGIN
SELECT convert(varchar,@datefrom,111) + ' - ' + convert(varchar,@dateto,111) as DATERANGE,
@DEPARTMENTID AS DEPARTMENTID,
BIONO,NAME,SUM(REGULAR_WORKING_DAYS) - SUM(REGULAR_HOLIDAYS) - SUM(SPECIAL_HOLIDAYS) AS REG_WD,
SUM(REGULAR_HOLIDAYS) AS REG_HD,
SUM(SPECIAL_HOLIDAYS) AS SPEC_HD,
(DATEDIFF(day, @DATEFROM, @DATETO) + 1 )-
(SUM(REGULAR_WORKING_DAYS)+@sundaysCount)
 as ABSENT,
SUM(OVERTIME) AS OVERTIME,
SUM(LATE_UNDERTIME) AS LATE
FROM VIEW_ATTENDANCE_SUMMARY
WHERE DATE BETWEEN @DATEFROM AND @DATETO
GROUP BY
BIONO,NAME
END