CREATE PROCEDURE [dbo].[GET_BREAKTIME_LATE_SUMMARY]
@DATEFROM AS DATETIME2,
@DATETO AS DATETIME2,
@DEPARTMENTID AS VARCHAR(255)
AS
BEGIN
SELECT convert(varchar,@datefrom,111) + ' - ' + convert(varchar,@dateto,111) as DATERANGE,
@DEPARTMENTID AS DEPARTMENTID,
BIONO,NAME,SUM(LATE) AS LATE
FROM VIEW_BREAKTIME_LATE_SUMMARY
WHERE [DATE] BETWEEN @DATEFROM AND @DATETO
GROUP BY
BIONO,NAME
END