CREATE PROCEDURE [dbo].[PRINT_CHECK]
@COMMAND AS INT,
@TRANSNO AS VARCHAR(255)
AS
BEGIN
IF @COMMAND = 0 BEGIN
SELECT CHECKNO,CARDNAME,AMOUNT,CHECKDATE
FROM tblCheckTransaction
INNER JOIN tblCardsProfile on tblCardsProfile.cardID = tblCheckTransaction.CARDID
where [NO] = @TRANSNO
END
ELSE IF @COMMAND = 1 BEGIN
DELETE tblCheckTransaction WHERE [NO] = @TRANSNO
END
END