<?xml version="1.0" encoding="utf-8"?><Database Name="DFCPS_MANAGEMENT_DB" Class="inventoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=DFCPS_MANAGEMENT_DB;User ID=sa" SettingsObjectName="DFCPS_MANUFACTURING_SYSTEM.My.MySettings" SettingsPropertyName="DFCPS_MANAGEMENT_DBConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblInvtry" Member="tblInvtries">
    <Type Name="tblInvtry">
      <Column Name="ITEMNO" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ITEMDESC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UNITCOST" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="UNIT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="BUYABLE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SELLABLE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="INVENTORABLE" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="COSTOFSALESACC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="INCOMEACC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ASSETACC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MINIMUMSTOCK" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblItem_issuance" Member="tblItem_issuances">
    <Type Name="tblItem_issuance">
      <Column Name="issuanceNo" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="refNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="transDate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="totalItemCount" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="totalCost" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="chargeToAccount" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="userID" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="notimesedit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lastdateedit" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblItemTransaction" Member="tblItemTransactions">
    <Type Name="tblItemTransaction">
      <Column Name="dateTrans" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="refNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="src" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="itemNo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UNITCOST" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="qty" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="job" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblSales_price" Member="tblSales_prices">
    <Type Name="tblSales_price">
      <Column Name="price_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="itemcode" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="date_set" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="ref" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>