ALTER TABLE [dbo].[tblPDORFYTR]
    ADD CONSTRAINT [PK__tblPDORF__DD194F9B27F8EE98] PRIMARY KEY CLUSTERED ([PDORFYITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

