ALTER TABLE [dbo].[tblAccHeader]
    ADD CONSTRAINT [PK__tblAccHe__F19EB54B04CFADEC] PRIMARY KEY CLUSTERED ([accHeaderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

