ALTER TABLE [dbo].[tblJob_items]
    ADD CONSTRAINT [PK__tblJob_i__3214EC273CF40B7E] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

