ALTER TABLE [dbo].[tblTrans_update_logs]
    ADD CONSTRAINT [PK__tblTrans__834A36187F4BDEC0] PRIMARY KEY CLUSTERED ([UPDATE_LOG_ID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

