ALTER TABLE [dbo].[tblDYR]
    ADD CONSTRAINT [PK__tblDYR__7D380F9516CE6296] PRIMARY KEY CLUSTERED ([DYNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

