ALTER TABLE [dbo].[tblSales_price]
    ADD CONSTRAINT [PK__tblSales__1681726D3BFFE745] PRIMARY KEY CLUSTERED ([price_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

