ALTER TABLE [dbo].[tblPayable]
    ADD CONSTRAINT [PK__tblPayab__771C61834E9398CC] PRIMARY KEY CLUSTERED ([PaymentbillNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

