ALTER TABLE [dbo].[tblVoucher]
    ADD CONSTRAINT [PK__tblVouch__3AD31D6E56BECA79] PRIMARY KEY CLUSTERED ([VoucherNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

