ALTER TABLE [dbo].[tblSalesQuotation]
    ADD CONSTRAINT [PK__tblQuota__C77149AC6B99EBCE] PRIMARY KEY CLUSTERED ([quoteNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

