ALTER TABLE [dbo].[tblSpendMoneyInvoice]
    ADD CONSTRAINT [PK__tblSpend__AC5D4C8D7D2E8C24] PRIMARY KEY CLUSTERED ([spendMoneyInvoiceNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

