ALTER TABLE [dbo].[tblCollection]
    ADD CONSTRAINT [PK__tblColle__5BCE7FFE04FA9675] PRIMARY KEY CLUSTERED ([collectionNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

