ALTER TABLE [dbo].[TBLUSERINFO]
    ADD CONSTRAINT [PK__TBLUSERI__7B9E7F357C3A67EB] PRIMARY KEY CLUSTERED ([USERID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

