ALTER TABLE [dbo].[tblPaid]
    ADD CONSTRAINT [PK__tblPaid__22AAA20251EF2864] PRIMARY KEY CLUSTERED ([PAYNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

