ALTER TABLE [dbo].[tblJobOrder]
    ADD CONSTRAINT [PK__tblJobOr__077C941A3FD07829] PRIMARY KEY CLUSTERED ([JONO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

