ALTER TABLE [dbo].[tblDR]
    ADD CONSTRAINT [PK__tblDR__23BF5EC64589517F] PRIMARY KEY CLUSTERED ([DRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

