ALTER TABLE [dbo].[tblOffenses]
    ADD CONSTRAINT [PK__tblOffen__8ADB78AE32E0915F] PRIMARY KEY CLUSTERED ([offenseID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

