ALTER TABLE [dbo].[tblUsers]
    ADD CONSTRAINT [PK__tblUsers__CB9A1CDF13A7DD28] PRIMARY KEY CLUSTERED ([userID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

