ALTER TABLE [dbo].[tblCrusher]
    ADD CONSTRAINT [PK__tblCrush__81858BA506CD04F7] PRIMARY KEY CLUSTERED ([CRUSHERNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

