ALTER TABLE [dbo].[tblSpendMoney]
    ADD CONSTRAINT [PK__tblSpend__37872DA43DD3211E] PRIMARY KEY CLUSTERED ([spendMoneyNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

