ALTER TABLE [dbo].[tblRMW]
    ADD CONSTRAINT [PK__tblRMW__027679D62DB1C7EE] PRIMARY KEY CLUSTERED ([RMWNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

