ALTER TABLE [dbo].[tblAdjustmentTR]
    ADD CONSTRAINT [PK__tblAdjus__3A95692D4460231C] PRIMARY KEY CLUSTERED ([ADJITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

