ALTER TABLE [dbo].[tblMRTR]
    ADD CONSTRAINT [PK__tblMRTR__2843B2DD0EA330E9] PRIMARY KEY CLUSTERED ([MRITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

