ALTER TABLE [dbo].[tblAccDepartment]
    ADD CONSTRAINT [PK__tblAccDe__3005163900FF1D08] PRIMARY KEY CLUSTERED ([AccDepartmentNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

