ALTER TABLE [dbo].[tblDoffed]
    ADD CONSTRAINT [PK__tblDoffe__FABBB773164452B1] PRIMARY KEY CLUSTERED ([rollID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

