ALTER TABLE [dbo].[tblCrusherTR]
    ADD CONSTRAINT [PK__tblCrush__35267BE20A9D95DB] PRIMARY KEY CLUSTERED ([CRUSHERITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

