ALTER TABLE [dbo].[tblQATR]
    ADD CONSTRAINT [PK__tblQATR__B0F5CD0421B6055D_copy1] PRIMARY KEY CLUSTERED ([QAITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

