ALTER TABLE [dbo].[tempAccCosting]
    ADD CONSTRAINT [PK__tempAccC__3213E83F5ACF527F] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

