ALTER TABLE [dbo].[tblCheckbook]
    ADD CONSTRAINT [PK__tblCheck__7C08525E662B2B3B] PRIMARY KEY CLUSTERED ([checkbookID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

