ALTER TABLE [dbo].[tblAccEntry]
    ADD CONSTRAINT [PK__tblAccEn__D124D3F5515009E6] PRIMARY KEY CLUSTERED ([entryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

