ALTER TABLE [dbo].[tblInkMixtureTR]
    ADD CONSTRAINT [PK__tblInkMi__7E5B636E7FEAFD3E] PRIMARY KEY CLUSTERED ([MIXNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

