ALTER TABLE [dbo].[tblAccSubHeader]
    ADD CONSTRAINT [PK__tblAccSu__A510804F08A03ED0] PRIMARY KEY CLUSTERED ([accSubHeaderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

