ALTER TABLE [dbo].[PayAccount]
    ADD CONSTRAINT [PK__PayAccou__3214D4A83F865F66] PRIMARY KEY CLUSTERED ([No] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

