ALTER TABLE [dbo].[tblLoomSectionTR]
    ADD CONSTRAINT [PK__tblLoomS__311E102F03317E3D] PRIMARY KEY CLUSTERED ([LTRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

