ALTER TABLE [dbo].[tblCardsProfile]
    ADD CONSTRAINT [PK__tblCards__4D5BC4B10C70CFB4] PRIMARY KEY CLUSTERED ([cardID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

