ALTER TABLE [dbo].[tblInvtry]
    ADD CONSTRAINT [PK__tblInvtr__7A8D6CD055209ACA] PRIMARY KEY CLUSTERED ([ITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

