ALTER TABLE [dbo].[tblCardsBalance]
    ADD CONSTRAINT [PK__tblCards__0F54378F10416098] PRIMARY KEY CLUSTERED ([cardBalNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

