ALTER TABLE [dbo].[tblTimeTable]
    ADD CONSTRAINT [PK__tblTimeT__FE740D0A00FF1D08] PRIMARY KEY CLUSTERED ([TIMETABLEID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

