ALTER TABLE [dbo].[tblItem_units]
    ADD CONSTRAINT [PK__tblItem___D3AF5BD742ACE4D4] PRIMARY KEY CLUSTERED ([unit_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

