ALTER TABLE [dbo].[tblSettingsVariable]
    ADD CONSTRAINT [PK__tblSetti__3213E83F30C33EC3] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

