ALTER TABLE [dbo].[tblCOA]
    ADD CONSTRAINT [PK__tblCOA__A47197051BB31344] PRIMARY KEY CLUSTERED ([accNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

