ALTER TABLE [dbo].[tblMR]
    ADD CONSTRAINT [PK__tblMR__6C616B8922401542] PRIMARY KEY CLUSTERED ([MRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

