ALTER TABLE [dbo].[tblAdjustment]
    ADD CONSTRAINT [PK__tblAdjus__B264F538408F9238] PRIMARY KEY CLUSTERED ([ADJNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

