ALTER TABLE [dbo].[tblSalesCashInvoice]
    ADD CONSTRAINT [PK__tblSales__480A1A9F3E3D3572] PRIMARY KEY CLUSTERED ([salesCashInvoiceNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

