ALTER TABLE [dbo].[tblLoomSection]
    ADD CONSTRAINT [PK__tblLoomS__1D3C85091F63A897] PRIMARY KEY CLUSTERED ([CLSNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

