ALTER TABLE [dbo].[tblLeavex]
    ADD CONSTRAINT [PK__tblLeave__CB45E81B1273C1CD_copy1] PRIMARY KEY CLUSTERED ([leaveNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

