ALTER TABLE [dbo].[tblFPITR]
    ADD CONSTRAINT [PK__tblFPITR__0E8C0D7E440B1D61] PRIMARY KEY CLUSTERED ([fpiItemNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

