ALTER TABLE [dbo].[tblBreaktime]
    ADD CONSTRAINT [PK__tblBreak__3214D4A85F492382] PRIMARY KEY CLUSTERED ([No] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

