ALTER TABLE [dbo].[Accounts_Payable]
    ADD CONSTRAINT [PK__Accounts__198D08613E082B48] PRIMARY KEY CLUSTERED ([refNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

