ALTER TABLE [dbo].[tblDYTR]
    ADD CONSTRAINT [PK__tblDYTR__4D1D1001267ABA7A] PRIMARY KEY CLUSTERED ([DYRITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

