ALTER TABLE [dbo].[General Journal]
    ADD CONSTRAINT [PK__General __08FCDDBD4A6E022D] PRIMARY KEY CLUSTERED ([GJNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

