ALTER TABLE [dbo].[tblLooms]
    ADD CONSTRAINT [PK__tblLooms__FF87A8231C873BEC] PRIMARY KEY CLUSTERED ([loomNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

