ALTER TABLE [dbo].[Accounts_Receivable]
    ADD CONSTRAINT [PK__Accounts__198D086141D8BC2C] PRIMARY KEY CLUSTERED ([refNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

