ALTER TABLE [dbo].[tblQA]
    ADD CONSTRAINT [PK__tblQA__DFA26A132AD55B43] PRIMARY KEY CLUSTERED ([QANO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

