ALTER TABLE [dbo].[tblPrinting]
    ADD CONSTRAINT [PK__tblPrint__BC4023C213F1F5EB] PRIMARY KEY CLUSTERED ([PRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

