ALTER TABLE [dbo].[tblRMAdjustment]
    ADD CONSTRAINT [PK__tblRMAdj__6C26689F7D439ABD] PRIMARY KEY CLUSTERED ([RMADJNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

