ALTER TABLE [dbo].[tblApprovedTransaction]
    ADD CONSTRAINT [PK__tblAppro__3213E83F5FBE24CE] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

