ALTER TABLE [dbo].[tblReceivedTR]
    ADD CONSTRAINT [PK__tblRecei__AB1B4CDB7869D707] PRIMARY KEY CLUSTERED ([RITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

