ALTER TABLE [dbo].[tblCompany]
    ADD CONSTRAINT [PK__tblCompa__AD5459B0534D60F1] PRIMARY KEY CLUSTERED ([companyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

