ALTER TABLE [dbo].[tblRMAdjustmentTR]
    ADD CONSTRAINT [PK__tblRMAdj__75B0196601142BA1] PRIMARY KEY CLUSTERED ([RMADJITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

