ALTER TABLE [dbo].[tblRMP]
    ADD CONSTRAINT [PK__tblRMW__027679D62DB1C7EE_copy1] PRIMARY KEY CLUSTERED ([RMPNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

