ALTER TABLE [dbo].[tblRecycle]
    ADD CONSTRAINT [PK__tblRecyc__E30535FC6EF57B66] PRIMARY KEY CLUSTERED ([RRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

