ALTER TABLE [dbo].[tblRollPrintingTR]
    ADD CONSTRAINT [PK__tblPrint__8B4DAE8E7C1A6C5A] PRIMARY KEY CLUSTERED ([PRINTINGNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

