ALTER TABLE [dbo].[tblStockOut]
    ADD CONSTRAINT [PK__tblStock__FF786853308E3499] PRIMARY KEY CLUSTERED ([STONO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

