ALTER TABLE [dbo].[tblDepartmentProfile]
    ADD CONSTRAINT [PK__tblDepar__F9B84CDE17E28260] PRIMARY KEY CLUSTERED ([departmentNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

