ALTER TABLE [dbo].[tblPDORFY]
    ADD CONSTRAINT [PK__tblPDORF__C354A741251C81ED] PRIMARY KEY CLUSTERED ([FYRNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

