ALTER TABLE [dbo].[tblStockOutTR]
    ADD CONSTRAINT [PK__tblStock__140DBD236462DE5A] PRIMARY KEY CLUSTERED ([STOITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

