ALTER TABLE [dbo].[tblSalesOrder]
    ADD CONSTRAINT [PK__tblSales__AE178AE267C95AEA] PRIMARY KEY CLUSTERED ([salesOrderNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

