ALTER TABLE [dbo].[tblManualPrintingTR]
    ADD CONSTRAINT [PK__tblManua__E4F623D603BB8E22] PRIMARY KEY CLUSTERED ([PRINTMANUALNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

