ALTER TABLE [dbo].[tblRecycleInputTR]
    ADD CONSTRAINT [PK__tblRecyc__DEA9C5A872C60C4A] PRIMARY KEY CLUSTERED ([RRINPUTNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

