ALTER TABLE [dbo].[tblOrderReleasedTR]
    ADD CONSTRAINT [PK__tblOrder__6F4FC2D54865BE2A] PRIMARY KEY CLUSTERED ([DRITEMNO] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

