ALTER TABLE [dbo].[tblInfractions]
    ADD CONSTRAINT [PK__tblInfra__40A575AF2E1BDC42] PRIMARY KEY CLUSTERED ([infractionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

