ALTER TABLE [dbo].[tblCheckVoucher]
    ADD CONSTRAINT [PK__tblCheck__37118F330CFADF99] PRIMARY KEY CLUSTERED ([checkVoucherNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

