ALTER TABLE [dbo].[tblFPI]
    ADD CONSTRAINT [PK__tblFPI__DE5D35015A846E65] PRIMARY KEY CLUSTERED ([fpiNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

