ALTER TABLE [dbo].[tblLeaveType]
    ADD CONSTRAINT [PK__tblLeave__CEFA32984CA06362] PRIMARY KEY CLUSTERED ([leaveTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

